### ISSUE TITLE
Sort out project priorities

### ISSUE THREAD

**Issue by phildotdev** [PJL101/wpkit#28]
Each issue needs reassessing and reprioritising with the following urgent decisions
- [ ] do we switch to centos?
- [ ] do we switch to maria db?
- [ ] de we switch to puppet?
